
CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    phone_number VARCHAR(255) NOT NULL,
    user_type VARCHAR(31) NOT NULL,
    user_role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    is_taken BOOLEAN,
    created_at TIMESTAMP,
    doctor_id BIGINT,
    patient_id BIGINT,
    FOREIGN KEY (doctor_id) REFERENCES app_user(id),
    FOREIGN KEY (patient_id) REFERENCES app_user(id)
);